<? if( !defined( '_AUTOGAN' ) && !defined( '_VALID_VVM' ) ) die( 'Restricted access' ); ?>
<script type ="text/javascript">
var Donde_Estoy=empty($.cookie("Cookie_Donde_Estoy"))?"Post_DIV":$.cookie("Cookie_Donde_Estoy"),Lugar_Info=$.cookie("Cookie_Lugar_Info");$(".cargador_img_subir").click(function(){var a="#cargador_img_"+$(this).attr("id");0!=$(a+" #cargador_cant_img").text().trim()&&Cuadro_Dialogo_img_Entrar(a,"cargador_img_output_ok",$(a+" #cargador_img_cropear").text().trim(),"no",$(a+" #cargador_cant_alto").text().trim(),$(a+" #cargador_img_ancho").text().trim(),$(a+" #cargador_img_destino").text().trim())});
function Cargador_img_warper(a,b){$(a+" .cargador_img_lista_archivos").append('<li id="'+Analizar_IMG(b)+'"><span class="Url_Img">'+b+'</span> (image/jpeg) - <span  class="texto_field "><a href="javascript:Eliminar_img_warper(\''+a+"','"+b+'\')" class="cargador_img_opcion"><img class="valign" alt="" src=""/><span class="Modern_Pics">X</span>Eliminar Imagen</a></span></li>');var d=$(a+" #cargador_cant_img").text().trim(),d=d-1;0==d&&$(a+" .cargador_img_subir").fadeOut("fast");$(a+" #cargador_cant_img").text(d);
$(a+"_err").html("&nbsp;")}function Eliminar_img_warper(a,b){var d="ajx=EIMG&Img_eli="+encodeURIComponent(b);$.ajax({cache:!1,type:"POST",url:"AJAX.php",data:d,success:function(){var d=$(a+" #cargador_cant_img").text().trim();0==d&&$(a+" .cargador_img_subir").fadeIn("fast");$(a+" #"+Analizar_IMG(b)).detach();$(a+" #cargador_cant_img").text(d+1)}})}
function Enviar_Post(a){var b=$("#Form_Post_DIV input[type!='button'], #Form_Post_DIV textarea, #Form_Post_DIV select"),d=$("#Form_Post_DIV .cargador_img");if(0==Validar_Formulario(b,d))switch($("#Form_Post_DIV fieldset").fadeTo("fast",0.3),$("#Form_Post_DIV .cargando").fadeTo("fast",1),b=Generar_LaData(b,d),a){case 1:$.ajax({type:"POST",url:"AJAX.php",data:b+"ajx=PPP",success:function(a){$("#Post_Preview").html('<div class="separador"></div><br/>'+a+'<br/> &nbsp; <div id="" class="DIV_FORM"><form><fieldset><input value="Guardar" name="guardar" id="guardar" type="button" onclick="Enviar_Post(2)" class="boton_es" /></fieldset></form></div>').slideDown("fast",
function(){$("#Form_Post_DIV fieldset").fadeTo("fast",1);$("#Form_Post_DIV .cargando").fadeTo("fast",0,function(){$(this).hide()});Google_Maps_initialize();Codificar_Direccion($("#Form_Post_DIV #direccion").val()+$("#Form_Post_DIV #reg_prov").val(),$("#Form_Post_DIV #mostra_gmap").val());$(".pic a").lightBox({imageLoading:"img/loading.gif",imageBtnClose:"img/cerrar.gif",imageBtnPrev:"img/ant.gif",imageBtnNext:"img/sig.gif",containerResizeSpeed:350,txtImage:"Imagen",txtOf:"de"});$.scrollTo("#Post_Preview",
1E3)})}});break;case 2:$.scrollTo("#cuerpo",500),$("#Post_Preview").delay(500).slideUp("fast"),"agregar"==Lugar_Info?(b+="ajx=AEP",$.ajax({type:"POST",url:"AJAX.php",data:b,success:function(a){a=jQuery.parseJSON(a);$("#Form_Post_DIV fieldset").fadeTo("fast",1);$("#Form_Post_DIV .cargando").fadeTo("fast",0,function(){$(this).hide()});1==a.OK?(Resetear_formulario("Form_Post_DIV"),$("#Aviso_DIV").fadeIn("fast"),$("#Aviso_DIV .aviso .aviso_texto").html('Propiedad Agregada, click <a href="'+a.Data+'" target="blank" alt="" title="">AQUI</a> para ir a al post')):
alert("UP's hubo un error al cargar la base de datos. Intente de nuevo!")}})):(b+="ajx=EEP",$.ajax({type:"POST",url:"AJAX.php",data:b,success:function(a){a=jQuery.parseJSON(a);$("#Form_Post_DIV fieldset").fadeTo("fast",1);$("#Form_Post_DIV .cargando").fadeTo("fast",0,function(){$(this).hide()});1==a.OK?(Resetear_formulario("Form_Post_DIV"),$("#Aviso_DIV").fadeIn("fast"),$("#Aviso_DIV .aviso .aviso_texto").html('Propiedad Editada, click <a href="'+a.Data+'" target="blank" alt="" title="">AQUI</a> para ir a al post')):
alert("UP's hubo un error al cargar la base de datos. Intente de nuevo!")}}))}}
function Borrar_Editar(a){function b(a,b){a="#cargador_img_slide_"+a;IMGS=jQuery.parseJSON(b);for(var d=IMGS.length,c=0;c<d-1;c++)Cargador_img_warper(a,IMGS[c])}var d=$("#Form_Edit_borrar_DIV input[type!='button']"),e=Validar_Formulario(d,"");if(0==e){$("#Form_Edit_borrar_DIV fieldset").fadeTo("fast",0.3);$("#Form_Edit_borrar_DIV .cargando").fadeTo("fast",1);var c="";$.each(d,function(){c=c+$(this).attr("id")+"="+encodeURIComponent(sValidosarCadena($(this).val()))+"&"});switch(a){case 1:c+="ajx=PPB";
$.ajax({type:"POST",url:"AJAX.php",data:c,success:function(a){var b=jQuery.parseJSON(a);1==b.OK?$("#Post_Preview").html('<div class="separador"></div><br/>'+b.post+'<br/> &nbsp; <div id="" class="DIV_FORM"><form><fieldset><input value="'+("borrar"==Lugar_Info?"Borrar":"Editar")+'" name="Borrar_Editar_boton" id="Borrar_Editar_boton" type="button" onclick="Borrar_Editar(2)" class="boton_es" /></fieldset></form></div>').slideDown("fast",function(){$("#Form_Edit_borrar_DIV fieldset").fadeTo("fast",1);
$("#Form_Edit_borrar_DIV .cargando").fadeTo("fast",0,function(){$(this).hide()});Google_Maps_initialize();Codificar_Direccion(b.direccion+", "+b.region_provincia,b.mostra_gmap);$(".pic a").lightBox({imageLoading:"img/loading.gif",imageBtnClose:"img/cerrar.gif",imageBtnPrev:"img/ant.gif",imageBtnNext:"img/sig.gif",containerResizeSpeed:350,txtImage:"Imagen",txtOf:"de"});$.scrollTo("#Post_Preview",1E3)}):($("#Form_Edit_borrar_DIV fieldset").fadeTo("fast",1),$("#Form_Edit_borrar_DIV .cargando").fadeTo("fast",
0,function(){$(this).hide()}),alert("La propiedad no existe!"))}});break;case 2:switch(Lugar_Info){case "borrar":confirm("Seguro que deseas borrar esta propiedad??")?(c+="ajx=LPB",$.scrollTo("#cuerpo",500),$("#Post_Preview").delay(500).slideUp("fast"),$.ajax({type:"POST",url:"AJAX.php",data:c,success:function(a){jQuery.parseJSON(a);$("#Form_Edit_borrar_DIV fieldset").fadeTo("fast",1);$("#Form_Edit_borrar_DIV .cargando").fadeTo("fast",0,function(){$(this).hide()});Resetear_formulario("Form_Edit_borrar_DIV");
$("#Aviso_DIV").fadeIn("fast");$("#Aviso_DIV .aviso .aviso_texto").html("Propiedad Eliminada")}})):($.scrollTo("#cuerpo",500),$("#Post_Preview").delay(500).slideUp("fast",function(){$("#Form_Edit_borrar_DIV fieldset").fadeTo("fast",1);$("#Form_Edit_borrar_DIV .cargando").fadeTo("fast",0,function(){$(this).hide()})}),Resetear_formulario("Form_Edit_borrar_DIV"));break;case "edit":$.scrollTo("#cuerpo",500),$("#Post_Preview").delay(500).slideUp("fast"),c+="ajx=PTP",$.ajax({type:"POST",url:"AJAX.php",
data:c,success:function(a){a=jQuery.parseJSON(a);1==a.OK?($("#Form_Post_DIV #info_id").val(a.post.ID),$("#Form_Post_DIV #titulo").val(limpiar(a.post.titulo)),$("#Form_Post_DIV #descripcion_textarea").val(limpiar(a.post.descripcion)),""!=a.post.localidad&&$("#Form_Post_DIV #localidad").val(limpiar(a.post.localidad)),""!=a.post.suptotal&&$("#Form_Post_DIV #suptotal").val(limpiar(a.post.suptotal)),""!=a.post.mtdefrente&&$("#Form_Post_DIV #mtdefrente").val(limpiar(a.post.mtdefrente)),""!=a.post.supcubierta&&
$("#Form_Post_DIV #supcubierta").val(limpiar(a.post.supcubierta)),""!=a.post.ndeplantas&&$("#Form_Post_DIV #ndeplantas").val(limpiar(a.post.ndeplantas)),""!=a.post.dormitorios&&$("#Form_Post_DIV #dormitorios").val(limpiar(a.post.dormitorios)),""!=a.post.comodidades&&$("#Form_Post_DIV #comodidades").val(limpiar(a.post.comodidades)),""!=a.post.seguridad&&$("#Form_Post_DIV #seguridad").val(limpiar(a.post.seguridad)),""!=a.post.banios&&$("#Form_Post_DIV #banios").val(limpiar(a.post.banios)),""!=a.post.lavanderia&&
$("#Form_Post_DIV #lavanderia").val(limpiar(a.post.lavanderia)),""!=a.post.terraza&&$("#Form_Post_DIV #terraza").val(limpiar(a.post.terraza)),""!=a.post.jardin&&$("#Form_Post_DIV #jardin").val(limpiar(a.post.jardin)),""!=a.post.patio&&$("#Form_Post_DIV #patio").val(limpiar(a.post.patio)),""!=a.post.cochera&&$("#Form_Post_DIV #cochera").val(limpiar(a.post.cochera)),""!=a.post.antiguedad&&$("#Form_Post_DIV #antiguedad").val(limpiar(a.post.antiguedad)),""!=a.post.asador_quincho&&$("#Form_Post_DIV #asador_quincho").val(limpiar(a.post.asador_quincho)),
""!=a.post.cerrado_perimetral&&$("#Form_Post_DIV #cerrado_perimetral").val(limpiar(a.post.cerrado_perimetral)),""!=a.post.gas&&$("#Form_Post_DIV #gas").val(limpiar(a.post.gas)),""!=a.post.calefacccion&&$("#Form_Post_DIV #calefacccion").val(limpiar(a.post.calefacccion)),""!=a.post.cloacas&&$("#Form_Post_DIV #cloacas").val(limpiar(a.post.cloacas)),""!=a.post.piscina&&$("#Form_Post_DIV #piscina").val(limpiar(a.post.piscina)),""!=a.post.org_publicos_cercanos&&$("#Form_Post_DIV #org_publicos_cercanos").val(limpiar(a.post.org_publicos_cercanos)),
""!=a.post.escritura&&$("#Form_Post_DIV #escritura").val(limpiar(a.post.escritura)),$("#Form_Post_DIV #moneda option[value="+a.post.moneda+"]").attr("selected","selected"),$("#Form_Post_DIV #operacion option[value="+a.post.operacion+"]").attr("selected","selected"),$("#Form_Post_DIV #tipoinmueble option[value="+a.post.tipo_inmueble+"]").attr("selected","selected"),$("#Form_Post_DIV #mostra_gmap option[value="+a.post.mostra_gmap+"]").attr("selected","selected"),b("Google_M",a.post.google_map_pic),
b("Portada",a.post.portada_pic),b("Galeria",a.post.galeria_pic),b("FB_Pic",a.post.FB_pic),$("#Form_Post_DIV #precio").val(limpiar(a.post.precio)),$("#Form_Post_DIV #direccion").val(limpiar(a.post.direccion)),$("#Form_Post_DIV #reg_prov").val(limpiar(a.post.region_provincia)),$("#Form_Post_DIV #tag").val(limpiar(a.post.tags)),Cambiar_Lugar("editar_post")):alert("La propiedad no existe!");$("#Form_Edit_borrar_DIV fieldset").fadeTo("fast",1);$("#Form_Edit_borrar_DIV .cargando").fadeTo("fast",0,function(){$(this).hide()});
Resetear_formulario("Form_Edit_borrar_DIV")}})}}}else $.scrollTo("#Edit_borrar_DIV #"+e,500)}
function Manejar_mensajes(a,b){switch(a){case "R":$("#mensajes #mensajes_opcion").html('<img class="valign"><span class="Modern_Pics">}</span> CARGANDO...').css("color","#ccc").css("cursor","auto");$("#mensajes .mensajes_dia, #mensajes DD").slideUp("slow",function(){$(this).detach()});var d;$.ajax({cache:!1,type:"POST",url:"AJAX.php",data:"ajx=LMSG",success:function(a){$("#mensajes #mensajes_opcion").html('<img class="valign"><span class="Modern_Pics">R</span> Cargar Mensajes').css("color","#000").css("cursor",
"pointer");$("#mensajes").append(a);$(".cargando_table").fadeOut(0).hide();0==b&&$.scrollTo("#cuerpo",500)}});break;case "S":d="ajx=BMSG&id_post="+encodeURIComponent(b);var e=$("#mensajes_dd_"+b).attr("class").substring(18);$("#mensajes_cargando_"+b).fadeTo("slow",0.8);$(this).detach();$("#mensajes_dd_"+b).fadeTo("slow",0.2,function(){$(this).slideUp("fast",function(){$(this).detach();0==$(".mensajes_dd_fecha_"+e).length&&$("#mensajes_dt_fecha_"+e).fadeTo("fast",0.7).slideUp("slow",function(){$("#mensajes_dt_fecha_"+
e).detach();0==$("#mensajes .mensajes_dia").length&&$("#mensajes").append('<dt class="mensajes_dia"><span class="Modern_Pics">!</span> Nada por ac&aacute;...</dt>')})})});$.ajax({type:"POST",url:"AJAX.php",data:d,success:function(){}})}}
function Cargar_Correo(){$("#Form_Correo_DIV fieldset").fadeTo("fast",0.3);$("#Form_Correo_DIV .cargando").fadeTo("fast",1);$.ajax({type:"POST",url:"AJAX.php",data:"ajx=PEC",success:function(a){a=jQuery.parseJSON(a);1==a.OK?$("#Form_Correo_DIV #correo").val(limpiar(a.Data)):Resetear_formulario("Form_Correo_DIV");$("#Form_Correo_DIV fieldset").fadeTo("fast",1);$("#Form_Correo_DIV .cargando").fadeTo("fast",0,function(){$(this).hide()})}})}
function Editar_Correo(){var a=$("#Form_Correo_DIV input[type!='button']");0==Validar_Formulario(a,"")&&($("#Form_Correo_DIV fieldset").fadeTo("fast",0.3),$("#Form_Correo_DIV .cargando").fadeTo("fast",1),a=Generar_LaData(a,"")+"ajx=AEC",$.ajax({type:"POST",url:"AJAX.php",data:a,success:function(a){1==jQuery.parseJSON(a).OK?($("#Form_Correo_DIV fieldset").fadeTo("fast",1),$("#Form_Correo_DIV .cargando").fadeTo("fast",0,function(){$(this).hide()}),$("#Aviso_DIV").fadeIn("fast"),$("#Aviso_DIV .aviso .aviso_texto").html("Correo Actualizado")):
alert("UP's hubo un error al cargar la base de datos. Intente de nuevo!")}}))}
function Enviar_Info(a){var b=$("#Form_Info_DIV input[type!='button'], #Form_Info_DIV textarea");if(0==Validar_Formulario(b,""))switch($("#Form_Info_DIV fieldset").fadeTo("fast",0.3),$("#Form_Info_DIV .cargando").fadeTo("fast",1),b=Generar_LaData(b,""),a){case 1:$.ajax({type:"POST",url:"AJAX.php",data:b+"ajx=PPI",success:function(a){$("#Post_Preview").html('<div class="separador"></div><br/>'+a+'<br/> &nbsp;  <div id="" class="DIV_FORM"><form><fieldset><input value="Guardar" name="guardar" id="guardar" type="button" onclick="Enviar_Info(2)" class="boton_es" /></fieldset></form></div>').slideDown("fast",function(){$("#Form_Info_DIV fieldset").fadeTo("fast",
1);$("#Form_Info_DIV .cargando").fadeTo("fast",0,function(){$(this).hide()});$.scrollTo("#Post_Preview",1E3)})}});break;case 2:b+="ajx=GPI",$.scrollTo("#cuerpo",500),$("#Post_Preview").delay(500).slideUp("fast"),$.ajax({type:"POST",url:"AJAX.php",data:b,success:function(){$("#Form_Info_DIV fieldset").fadeTo("fast",1);$("#Form_Info_DIV .cargando").fadeTo("fast",0,function(){$(this).hide()});$("#Aviso_DIV").fadeIn("fast");$("#Aviso_DIV .aviso .aviso_texto").html('Propiedad Agregada, click <a href="'+
obj.Data+'" target="blank" alt="" title="">AQUI</a> para ir a al post')}})}}
function Cargar_Info(a){$("#Form_Info_DIV fieldset").fadeTo("fast",0.3);$("#Form_Info_DIV .cargando").fadeTo("fast",1);a="ajx=PLI&INF="+encodeURIComponent(a);$.ajax({type:"POST",url:"AJAX.php",data:a,success:function(a){a=jQuery.parseJSON(a);1==a.OK&&($("#Form_Info_DIV #titulo").val(limpiar(a.Data[0].titulo)),$("#Form_Info_DIV #contenido_textarea").val(limpiar(a.Data[0].contenido)),$("#Form_Info_DIV #tag").val(limpiar(a.Data[0].tags)),$("#Form_Info_DIV #info_id").val(limpiar(a.Data[0].ID)));$("#Form_Info_DIV fieldset").fadeTo("fast",
1);$("#Form_Info_DIV .cargando").fadeTo("fast",0,function(){$(this).hide()})}})}$(".menu dd").hide();$(".menu dl dt").click(function(){var a=$(this).parent().children("dd");"none"==$(a).css("display")&&($(".menu dd").fadeOut("fast"),$(a).fadeIn("fast"))});$(".menu").mouseleave(function(){$(".menu dd").fadeOut("fast")});
$(".menu dl dd").click(function(){var a=$(this).parents("dl").attr("id"),b=$(this).parents("form").attr("id"),d=$(this).attr("id"),e=$(this).parents("div").attr("id")+"_textarea",c="",f="",g="";switch(a){case "Estilo":f="["+d+"]";g="[/"+d+"]";break;case "Alinieacion":f="[align="+d+"]";g="[/align]";break;case "tamanio":f="[size="+d+"]";g="[/size]";break;case "Insertar":switch(d){case "link":c=prompt("Ingrese la URL que desea postear","http://");null!=c&&"http://"!=c?("http://"!=c.substring(0,7)&&"https://"!=
c.substring(0,8)&&(c="http://"+c),f="[url="+c+"]",g="[/url]",c=Analizar_URL(c)):c="";break;case "imagen":Cuadro_Dialogo_img_Entrar(b,e,"no","si",1E3,600,"img_post/MISC/");break;case "youtube":c=prompt("Ingrese la url del video de YouTube:\n\nEjemplo:\n http://www.youtube.com/watch?v=danYFxGnFxQ","Url del video de YouTube");null!=c&&"Url del video de YouTube"!=c&&(f="[align=center][youtube]"+c+"[/youtube][/align]\n",g="");c="";break;case "vimeo":c=prompt("Ingrese la url del video de Vimeo:\n\nEjemplo:\n http://vimeo.com/36509870",
"Url del video de Vimeo"),null!=c&&"Url del video de Vimeo"!=c&&(f="[align=center][vimeo]"+c+"[/vimeo][/align]\n",g=""),c=""}}TextArea_Warp(e,f,g,c)});
function TextArea_Warp(a,b,d,e){var a=$(Obtener_Formulario()+" #"+a),c=a.getSelection(),f=c.length,g=c.start,c=c.end,h=a.val().substring(0,g),g=a.val().substring(g,c),i=a.val().substring(c,a.val().length);if(1==c||2==c)c=f;c!=f&&(b+=e);a.val()==a.attr("title")?a.val(b+d):a.val(h+b+g+d+i);Tam_Seleccion=c+d.length+b.length;a.selectRange(Tam_Seleccion,Tam_Seleccion)}Construir_Drop();
function handleFileSelect(a){a.stopPropagation();a.preventDefault();for(var b=$($(a.target).children()),d=$(a.target).next("input[type=hidden]"),a=a.dataTransfer.files,e=0,c;c=a[e];e++)if(c.type.match("image.jpeg")){var f=new FileReader;f.onloadstart=function(){$(b).css("color","#acacac").text("Cargando Imagen...").fadeIn("fast").addClass("cargando_mas_post_gif")};f.onload=function(a){return function(){if(7E5>a.size){var c=new FormData;c.append("pic",a);c.append("ajx","IMG");c.append("crpr",$("#Cuadro_Dialogo_dropbox_cropear").val());
c.append("crpral",$("#Cuadro_Dialogo_dropbox_alto").val());c.append("crpran",$("#Cuadro_Dialogo_dropbox_ancho").val());c.append("dest",$("#Cuadro_Dialogo_dropbox_destino").val());$.ajax({cache:!1,contentType:!1,processData:!1,type:"POST",url:"AJAX.php",data:c,success:function(a){var c=jQuery.parseJSON(a);switch(c.status){case "imgmp":$(b).removeClass("cargando_mas_post_gif").css("color","red").text("La Imagen es demaciado pequenia").fadeIn("fast");break;case "error":$(b).removeClass("cargando_mas_post_gif").css("color",
"red").text("Error al cargar la imagen, Intente de nuevo").fadeIn("fast");break;default:$(d).val(c.status),a='<img class="miniatura" src="'+c.status+'" title=""/>',$(b).removeClass("cargando_mas_post_gif").html(a),$(".dropbox").css("width","auto"),$(function(a){var d;a("#"+a(b).attr("id")+" .miniatura").Jcrop({bgOpacity:0.5,bgColor:"white",addClass:"jcrop-light",allowSelect:!1,onSelect:Actualizar_Coordenadas},function(){d=this;d.setOptions({bgFade:!0});d.ui.selection.addClass("jcrop-selection");var b=
parseInt(a("#Cuadro_Dialogo_dropbox IMG").outerWidth())/c.width,e=parseInt(a("#Cuadro_Dialogo_dropbox IMG").outerHeight())/c.height,b=parseInt(a("#Cuadro_Dialogo_dropbox_ancho").val())*b,e=parseInt(a("#Cuadro_Dialogo_dropbox_alto").val())*e;"no"!=a("#Cuadro_Dialogo_dropbox_cropear").val()?(d.setOptions({aspectRatio:b/e}),d.setOptions({minSize:[b,e]}),d.focus(),d.setSelect([0,0,b,e])):d.setSelect([0,0,100,100])})})}}})}else $(b).css("color","red").removeClass("cargando_mas_post_gif").text("La Imagen no debe superar los 700 KB").fadeIn("fast")}}(c);
f.readAsBinaryString(c)}else $(b).fadeOut("fast",function(){$(b).css("color","red").text("Solamente Imagenes JPG...").fadeIn("fast");$(d).val("")})}function handleDragOver(a){a.stopPropagation();a.preventDefault();a.dataTransfer.dropEffect="copy"}
function Construir_Drop(){DropArchivo_nombre="f_Cuadro_Dialogo_imagen_"+$(this).attr("id");$("#f_Cuadro_Dialogo_imagen .dropbox").attr("name",DropArchivo_nombre);var a=GE(DropArchivo_nombre);a.addEventListener("dragover",handleDragOver,!0);a.addEventListener("drop",handleFileSelect,!0)}var Cuadro_Dialogo_Nombre_Form="",Cuadro_Dialogo_Text_Area_Nombre="",Centrar_intervalo;$(".Cuadro_Dialogo").hide(function(){$(".Cuadro_Dialogo").css("visibility","visible");$(".Cuadro_Dialogo_imagen").hide()});
function Cuadro_Dialogo_img_Entrar(a,b,d,e,c,f,g){"no"!=d?$("#Cuadro_Dialogo_dropbox span").html("Tirar aca la imagen para el Post. Min. Alto: "+c+"px Min. Ancho: "+f+"px"):$("#Cuadro_Dialogo_dropbox span").html("Tirar aca la imagen para el Post.");$("#Cuadro_Dialogo_dropbox_cropear").val(d);$("#Cuadro_Dialogo_dropbox_textarea").val(e);$("#Cuadro_Dialogo_dropbox_alto").val(c);$("#Cuadro_Dialogo_dropbox_ancho").val(f);$("#Cuadro_Dialogo_dropbox_destino").val(g);$(".Cuadro_Dialogo_imagen").show();Cuadro_Dialogo_Nombre_Form=
a;Cuadro_Dialogo_Text_Area_Nombre=b;$(".Cuadro_Dialogo").fadeIn("fast")}
function Cuadro_Dialogo_img_Salir(){$(".Cuadro_Dialogo").fadeOut("fast",function(){if(empty($("#Cuadro_Dialogo_dropbox_output").text().trim())){var a=new FormData;a.append("ajx","CROP");a.append("CROP_IMG",$("#Cuadro_Dialogo_dropbox_output_ok").val());a.append("CROP_X",$("#Cuadro_Dialogo_dropbox_Crop_X").val());a.append("CROP_Y",$("#Cuadro_Dialogo_dropbox_Crop_Y").val());"si"==$("#Cuadro_Dialogo_dropbox_cropear").val()?(a.append("CROP_W",$("#Cuadro_Dialogo_dropbox_ancho").val()),a.append("CROP_H",
$("#Cuadro_Dialogo_dropbox_alto").val())):(a.append("CROP_W",$("#Cuadro_Dialogo_dropbox_Crop_W").val()),a.append("CROP_H",$("#Cuadro_Dialogo_dropbox_Crop_H").val()));a.append("CROP_RATIO",$("#Cuadro_Dialogo_dropbox_cropear").val());a.append("CROP_un_W",$("#Cuadro_Dialogo_dropbox IMG").outerWidth());a.append("CROP_un_H",$("#Cuadro_Dialogo_dropbox IMG").outerHeight());$.ajax({cache:!1,contentType:!1,processData:!1,type:"POST",url:"AJAX.php",data:a,success:function(){}});"si"==$("#Cuadro_Dialogo_dropbox_textarea").val()?
TextArea_Warp(Cuadro_Dialogo_Text_Area_Nombre," ","[align=center][img="+$("#Cuadro_Dialogo_dropbox_output_ok").val()+"][/align]",""):Cargador_img_warper(Cuadro_Dialogo_Nombre_Form,$("#Cuadro_Dialogo_dropbox_output_ok").val())}$("#Cuadro_Dialogo_dropbox_output").text("Tirar aca la imagen para el Post");$("#Cuadro_Dialogo_dropbox_ok").val("");$("#Cuadro_Dialogo_dropbox_alto").val("");$("#Cuadro_Dialogo_dropbox_ancho").val("");$("#Cuadro_Dialogo_dropbox_destino").val("");$("#Cuadro_Dialogo_dropbox_cropear").val("");
$("#Cuadro_Dialogo_dropbox_textarea").val("");$(".Cuadro_Dialogo_imagen").hide();$(".dropbox").css("width","900px")})}function Cuadro_Dialogo_Centrar(){$(".Cuadro_Dialogo").css("margin-top",-($(".Cuadro_Dialogo").outerHeight()/2));$(".Cuadro_Dialogo").css("margin-left",-($(".Cuadro_Dialogo").outerWidth()/2))}
function Actualizar_Coordenadas(a){$("#Cuadro_Dialogo_dropbox_Crop_X").val(a.x);$("#Cuadro_Dialogo_dropbox_Crop_Y").val(a.y);$("#Cuadro_Dialogo_dropbox_Crop_W").val(a.w);$("#Cuadro_Dialogo_dropbox_Crop_H").val(a.h)}
function Validar_Formulario(a,b){var d=0;$.each(b,function(){var a="#"+$(this).attr("id");0==$(a+" .cargado  r_img_lista_archivos LI").length&&($(a+"_err").html("Al  menos una imagen"),d=$(this).attr("id"))});$.each(a,function(){if((empty($(this).val())||$(this).val()==$(this).attr("title"))&&!$(this).hasClass("no_req"))$(Obtener_Formulario()+" #"+$(this).attr("id")+"_err").html("Campo Obligatorio"),listo=0,empty(d)&&(d=$(this).attr("id"))});"correo"==$(this).attr("id")&&!Validar_Mail($(this).val())&&
($("#Form_Correo_DIV #"+$(this).attr("id")+"_err").html("El Correo Electronico no es valido"),empty(d)&&(d=$(this).attr("id")));$.scrollTo(Obtener_Formulario()+" #"+d,500);return d}
function Generar_LaData(a,b){var d="";$.each(a,function(){d=$(this).hasClass("no_req")&&$(this).val()==$(this).attr("title")?d+$(this).attr("id")+"="+encodeURIComponent(sValidosarCadena(""))+"&":d+$(this).attr("id")+"="+encodeURIComponent(sValidosarCadena($(this).val()))+"&"});$.each(b,function(){var a=$(this).attr("id"),b=$("#"+a+" .cargador_img_lista_archivos LI"),f="[";$.each(b,function(){var a="#"+$(this).attr("id");f=f+'"'+$(a+" .Url_Img").text().trim()+'", '});f+='""]';d=d+a+"="+encodeURIComponent(f)+
"&"});return d}function Obtener_Formulario(){return"#Form_"+Donde_Estoy}function Analizar_URL(a){Ultimo_Slash=a.lastIndexOf("/",a.length-1);STR_Out=a.substring(0,Ultimo_Slash+1);if("http://"!=STR_Out)return STR_Out}function Analizar_IMG(a){Ultimo_Slash=a.lastIndexOf("/",a.length-1);Ultimo_Dot=a.lastIndexOf(".",a.length-1);return STR_Out=a.substring(Ultimo_Slash+1,Ultimo_Dot)}
function Cambiar_Lugar(a){$("#Post_Preview").slideUp("fast",function(){$(this).html("");$("#"+Donde_Estoy).slideUp("slow",function(){switch(a){case "agregar_post":Donde_Estoy="Post_DIV";Lugar_Info="agregar";Resetear_formulario("Form_Post_DIV");break;case "editar_post":Donde_Estoy="Post_DIV";Lugar_Info="editar";break;case "editar_post":Donde_Estoy="Post_DIV";Lugar_Info="editar_post";Resetear_formulario("Form_Post_DIV");break;case "borrar":Donde_Estoy="Edit_borrar_DIV";Lugar_Info="borrar";Resetear_formulario("Form_Edit_borrar_DIV");
break;case "edit":Donde_Estoy="Edit_borrar_DIV";Lugar_Info="edit";Resetear_formulario("Form_Edit_borrar_DIV");break;case "Correo":case "Correo_DIV":Donde_Estoy="Correo_DIV";Lugar_Info="";Cargar_Correo();break;case "Mensajes":case "Mensajes_DIV":Donde_Estoy="Mensajes_DIV";Lugar_Info="";Manejar_mensajes("R",0);break;case "servicios":case "quienes_somos":case "terminosycondiciones":Donde_Estoy="Info_DIV",Lugar_Info=a,Cargar_Info(Lugar_Info)}$(".aviso_cerrar").click();$("#"+Donde_Estoy).slideDown("slow",
function(){$.scrollTo("#botonera",500);Tamanio_Cargar()});$.cookie("Cookie_Donde_Estoy",Donde_Estoy,{expires:7});$.cookie("Cookie_Lugar_Info",Lugar_Info,{expires:7})})})}
function Resetear_formulario(a){var b=$("#"+a+" input[type!='button'], #"+a+" textarea, #"+a+" select"),a=$("#"+a+" .cargador_img");$.each(b,function(){$(this).val($(this).attr("title"))});$.each(a,function(){var a="#"+$(this).attr("id"),b=$(a+" .cargador_img_lista_archivos LI").length;$(a+" .cargador_img_lista_archivos LI").detach();$(a+" #cargador_cant_img").text(parseInt($(a+" #cargador_cant_img").text().trim())+b);$(a+" .cargador_img_subir").fadeIn("fast")})}
function permite(a,b){var d=String.fromCharCode(8),e=String.fromCharCode(9);switch(b){case "num":b="0123456789";break;case "car":b="abcdefghijklmn\u00f1opqrstuvwxyzABCDEFGHIJKLMN\u00d1OPQRSTUVWXYZ ";break;case "car_sim":b="abcdefghijklmn\u00f1opqrstuvwxyzABCDEFGHIJKLMN\u00d1OPQRSTUVWXYZ !$%&()=?\u00a1._-,;.:@*[]+{}";break;case "num_car":b="0123456789abcdefghijklmn\u00f1opqrstuvwxyzABCDEFGHIJKLMN\u00d1OPQRSTUVWXYZ ";break;case "num_sim":b="0123456789!$%&()=?\u00a1._-,;.:@*[]+{}";break;case "fecha":b=
"0123456789/";break;case "todo":b="!$%&()=?\u00a1._-,;.:@*[]+{}abcdefghijklmn\u00f1opqrstuvwxyzABCDEFGHIJKLMN\u00d1OPQRSTUVWXYZ 0123456789"}b=b+e+d;d=a||window.event;d=String.fromCharCode(d.charCode||d.keyCode);return-1!=b.indexOf(d)}function Login_Salir(){$.cookie("Login_Petrino_User","",{expires:7});$.cookie("Login_Petrino_Veri","",{expires:7});window.location.reload()}$(".aviso_cerrar").click(function(){$("#Aviso_DIV").fadeOut("normal",function(){$(this).css("display","none")})});
$(document).ready(function(){empty(Lugar_Info)?Cambiar_Lugar(Donde_Estoy):Cambiar_Lugar(Lugar_Info)});
</script>