<? 	if( !defined( '_AUTOGAN' ) && !defined( '_VALID_VVM' ) ) die( 'Restricted access' ); ?>
<script type="text/javascript">
<? if (bandera("gmap")) { ?>
var geocoder,map,infowindow=new google.maps.InfoWindow;function Google_Maps_initialize(){geocoder=new google.maps.Geocoder;var a={mapTypeId:google.maps.MapTypeId.SATELLITE};map=new google.maps.Map(document.getElementById("GoogleMap"),a)}
function Codificar_Direccion(a,c){var b=limpiar(a);geocoder.geocode({address:b},function(a,b){b==google.maps.GeocoderStatus.OK&&"si"==c?(map.setCenter(a[0].geometry.location),map.setZoom(17),new google.maps.Marker({map:map,position:a[0].geometry.location})):$("#GoogleMap").css("background","url("+$("#GoogleMap_default").text().trim()+")")})};
<? }else{ ?>
function Google_Maps_initialize(){}function Codificar_Direccion(){$("#GoogleMap").css("background","url("+$("#GoogleMap_default").text().trim()+")")};
<? } ?>
function onfocus_input(a){$(a).val()==$(a).attr("title")&&$(a).val("");$("form #"+$(a).attr("id")+"_err").html("&nbsp;")}function onblur_input(a){($(a).val()==$(a).attr("title")||""==$(a).val())&&$(a).val($(a).attr("title"))}
function sValidosarCadena(a){for(var c="",a=a.replace(/\u00bf/gi,"&iquest;"),a=a.replace(/\u00e1/gi,"&aacute;"),a=a.replace(/\u00e9/gi,"&eacute;"),a=a.replace(/\u00ed/gi,"&iacute;"),a=a.replace(/\u00f3/gi,"&oacute;"),a=a.replace(/\u00fa/gi,"&uacute;"),a=a.replace(/\u00f1/gi,"&ntilde;"),b=0;b<a.length;b++)0<a.charCodeAt(b)&&127>a.charCodeAt(b)&&(c+=a.charAt(b));return $.trim(c)}
function limpiar(a){a=a.replace(/&iquest;/gi,"\u00bf");a=a.replace(/&aacute;/gi,"\u00e1");a=a.replace(/&eacute;/gi,"\u00e9");a=a.replace(/&iacute;/gi,"\u00ed");a=a.replace(/&oacute;/gi,"\u00f3");a=a.replace(/&uacute;/gi,"\u00fa");return a=a.replace(/&ntilde;/gi,"\u00f1")}function Validar_Mail(a){return/\w{1,}[@][\w\-]{1,}([.]([\w\-]{1,})){1,3}$/.test(a)?!0:!1}
function Enviar_Comentario(){function a(a){$("form fieldset").fadeTo("slow",0.2);$("form  .cargando").fadeTo("slow",0.3,function(){$(this).removeClass("cargando_bg").html('<img class="valign">'+a).fadeTo("slow",1);$.each(c,function(){$(this).val($(this).attr("title"))})})}var c=$("form input[type!='button'], form textarea"),b=1,e="";Validar_Mail($("#email").val())?$("form #email_err").html("&nbsp;"):(b=0,e=$(this).attr("id"),$("form #email_err").html("El Correo Electronico no es valido"));$.each(c,
function(){if(empty($(this).val())||$(this).val()==$(this).attr("title"))$("form #"+$(this).attr("id")+"_err").html("Campo Obligatorio"),b=0,empty(e)&&(e=$(this).attr("id"))});if(1==b){var d="";$.each(c,function(){d=d+$(this).attr("id")+"="+encodeURIComponent(sValidosarCadena($(this).val()))+"&"});d+="ajx=AG";$("form fieldset").fadeTo("slow",0.3);$("form .cargando").fadeTo("slow",1);$.ajax({type:"POST",url:"<? echo traducir_url("AJAX.php") ?>",data:d,success:function(){a("Mensaje recibido!")},error:function(){a("Hubo un error! Intente m\u00e1s tarde.")}})}else $.scrollTo("form #"+
e,500,{offset:-50})};
function menu_estatico(){$(window).scrollTop()>=$("#cabecera_arriba").outerHeight()&&995<$(window).width()?$("#cabecera #menu").addClass("menu_estatico"):$("#cabecera #menu").removeClass("menu_estatico")}function Tamanio_Cargar(){$("form").each(function(){$("#"+$(this).attr("id")+" .cargando").css("height",$(this).outerHeight()+"px")})}
$(document).ready(function(){var b=1;$("input,select,textarea").each(function(){"hidden"!=this.type&&($(this).attr("tabindex",b),b++)});$(".cargando").hide().css("visibility","visible");$("input[type!='button'], textarea").focus(function(){onfocus_input($(this))});$("input[type!='button'], textarea").blur(function(){onblur_input($(this))});$("input,select,textarea").keypress(function(a){13==a.which&&(a="#"+$('[tabindex$="'+($(this).attr("tabindex")+1)+'"]').attr("id"),"button"==$(a).attr("type")?
$(a).click():$(a).focus())});Tamanio_Cargar()});$("#cabecera #menu A").mouseleave(function(){$(this).fadeTo("slow",1)}).mouseover(function(){$(this).fadeTo("slow",0.8)});
</script>
